version: '3.1'

services:
  mongo_router_server:
    network_mode: host
    image: mongo:latest
    restart: always
    ports:
      - 37019:37019
    volumes:
      - ./mongo_router_data:/data/mongodb
      - ./mongo_router_log:/data/logs
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - ./config/router.conf:/etc/mongo/mongodb_router.conf
      - ./config/security.key:/etc/mongo/mongo.key
      - ./run.sh:/data/run.sh
    command:
      bash /data/run.sh


