version: '3.1'

services:
  mongo_shard1_server:
    network_mode: host
    image: mongo:latest
    restart: always
    ports:
      - 37018:37018
    volumes:
      - ./mongo_shard1_data:/data/mongodb
      - ./mongo_shard1_log:/data/logs
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - ./config/shard1.conf:/etc/mongo/mongodb_shard1.conf
      - ./config/security.key:/etc/mongo/mongo.key
      - ./run.sh:/data/run.sh
    command:
      bash /data/run.sh


