version: '3.1'

services:
  mongo_config_server:
    network_mode: bridge
    image: mongo:latest
    restart: always
    ports:
      - 37017:37017
    volumes:
      - ./mongo_config_server_data:/data/mongodb
      - ./mongo_config_server_log:/data/logs
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - ./config/mongodb_config_server.conf:/etc/mongo/mongodb_config_server.conf
      - ./config/security.key:/etc/mongo/mongo.key
      - ./run.sh:/data/run.sh
    command:
      bash /data/run.sh


